language: java

addons:
  apt:
    packages:
      - libecpg-dev

services:
  - docker

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.cache/pip/
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_install:
  - sudo pip install pgsanity
  - curl https://raw.githubusercontent.com/hmcts/reform-api-docs/master/bin/publish-swagger-docs.sh > publish-swagger-docs.sh
  - sudo apt-get install jq
  - wget -O ./codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

script:
  - pgsanity --add-semicolon src/main/resources/db/migration/*.sql
  - ./gradlew test
  - ./gradlew integration

after_success:
  - ./gradlew jacocoTestReport
  - java -cp ./codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
  - test "$TRAVIS_BRANCH" = "master" && test "$TRAVIS_PULL_REQUEST" = "false" && sh ./publish-swagger-docs.sh
