version: '2.1'

services:
  send-letter-producer-service:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: docker.artifactory.reform.hmcts.net/reform/send-letter-producer-service
    container_name: send-letter-producer-service
    environment:
      - APPLICATION_INSIGHTS_DEV_MODE
      - APPLICATION_INSIGHTS_IKEY
      - S2S_URL
      # these environment variables are used by java-logging library
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
    ports:
      - $SERVER_PORT:$SERVER_PORT
