server:
  port: 8485

management:
  security:
    enabled: ${MANAGEMENT_SECURITY_ENABLED:true}

ttlInSeconds: ${TTL_IN_SECONDS:3600}

idam:
  s2s-auth:
    url: ${S2S_URL}

spring:
  application:
    name: Send Letter Provider
  datasource:
      url: jdbc:postgresql://${LETTER_TRACKING_DB_HOST:localhost}:${LETTER_TRACKING_DB_PORT:5432}/${LETTER_TRACKING_DB_NAME:letter-tracking}
      username: ${LETTER_TRACKING_DB_USER_NAME:postgres}
      password: ${LETTER_TRACKING_DB_PASSWORD:postgres}
      properties:
        charSet: UTF-8
      maxWaitForConnection: 1
      minSize: 8
      maxSize: 32
      evictionInterval: 10
      minIdleTime: 1 minute
      checkConnectionWhileIdle: true
      checkConnectionOnReturn: true
      removeAbandoned: true
      removeAbandonedTimeout: 60
      abandonWhenPercentageFull: 0
      testOnBorrow: true
      validationQuery: SELECT 1

servicebus:
  queue:
    connectionString: ${SERVICE_BUS_CONNECTION_STRING}
    messageTTLInDays: ${SERVICE_QUEUE_MESSAGE_TTL_IN_DAYS:7}
