server:
  port: 8485

management:
  security:
    enabled: ${MANAGEMENT_SECURITY_ENABLED:true}

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD:}

ttlInSeconds: ${TTL_IN_SECONDS:3600}

notify:
  stub: ${STUB_NOTIFY:false}

idam:
  s2s-auth:
    enabled: ${S2S_ENABLED:true}
    url: ${S2S_URL}
