server:
  port: 8485

management:
  security:
    enabled: ${MANAGEMENT_SECURITY_ENABLED:true}

ttlInSeconds: ${TTL_IN_SECONDS:3600}

idam:
  s2s-auth:
    url: ${S2S_URL}

spring:
  application:
    name: Send Letter Provider

servicebus:
  connectionString: ${SERVICE_BUS_CONNECTION_STRING}
  queue:
    messageTTLInDays: ${SERVICE_QUEUE_MESSAGE_TTL_IN_DAYS:7}
